DELETE FROM list_of_friends;
DELETE FROM film_likes;
DELETE FROM users;
ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1;
DELETE FROM films;
ALTER TABLE films ALTER COLUMN film_id RESTART WITH 1;